#!/bin/bash

SOURCE=yadt-minion-modular-config.md
OUTDIR=out

AVALANCHEDIR=$OUTDIR/avalanche


mkdir -p $OUTDIR

landslide -h > /dev/null 2>&1 || sudo apt-get install python-landslide
[[ -d $AVALANCHEDIR ]] || git clone https://github.com/arnehilmann/avalanche.git $AVALANCHEDIR
(
    cd res
    make
)
landslide $(basename $SOURCE .md).cfg
echo "file://$PWD/$OUTDIR/$(basename $SOURCE .md).html"
